server:
  port: 8006


spring:
  application:
    name: consul-provider-payment

  cloud:
    consul:  #consul服务器地址
      host: 127.0.0.1
      port: 8500
      discovery:
        #hostname
        service-name: ${spring.application.name} #该服务在consul中对外暴露的服务名称