server:
  port: 80


eureka:
  client:
    register-with-eureka: true #向eureka注册自己
    fetch-registry: true #要不要去注册中心获取其他服务的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

spring:
  application:
    name: OrderHystrix80